before_script:
  - chmod +x script/prepare_build.sh
  - ./script/prepare_build.sh
  - ruby -v
  - gem install bundler
  - cp config/application.yml.example config/application.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bundle --without postgres
  - RAILS_ENV=test bundle exec rake db:setup
specs:
  script: SIMPLECOV=true RAILS_ENV=test bundle exec rake spec
  parallel: 10

rubocop:
  script: bundle exec rubocop
  parallel: 10

brakeman:
  script: bundle exec brakeman
  parallel: 10
