env:
  - DB=mysql TRAVIS=true
  - DB=postgresql TRAVIS=true
before_install:
  - sudo apt-get install libicu-dev -y
  - gem install charlock_holmes -v="0.6.9"
branches:
  only:
    - 'master'
rvm:
  - 2.0.0
services:
  - mysql
  - postgresql
before_script:
  - "cp config/database.yml.$DB config/database.yml"
  - "cp config/application.yml.example config/application.yml"
  - "bundle exec rake db:create"
  - "bundle exec rake db:setup"
script: "bundle exec rake spec"
